# 应用服务 WEB 访问端口
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
